-- Create memories table for individual memory pages
CREATE TABLE IF NOT EXISTS memories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255),
  display_order INTEGER DEFAULT 0,
  photo_url TEXT,
  background_url TEXT,
  message TEXT,
  card_style VARCHAR(50) DEFAULT 'butterfly',
  photo_animation VARCHAR(50) DEFAULT 'gentle-float',
  card_animation VARCHAR(50) DEFAULT 'butterfly-reveal',
  photo_orientation VARCHAR(50) DEFAULT 'tilt-left',
  photo_position VARCHAR(50) DEFAULT 'center',
  card_position VARCHAR(50) DEFAULT 'right',
  music_url TEXT,
  music_volume DECIMAL(3,2) DEFAULT 0.7,
  music_loop BOOLEAN DEFAULT true,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for ordering
CREATE INDEX IF NOT EXISTS idx_memories_display_order ON memories(display_order ASC);
CREATE INDEX IF NOT EXISTS idx_memories_is_active ON memories(is_active);

-- Add updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_memories_updated_at BEFORE UPDATE ON memories
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Insert sample memory
INSERT INTO memories (title, display_order, message, card_style, is_active)
VALUES 
  ('Memory 1', 1, 'You make every moment beautiful.', 'butterfly', true)
ON CONFLICT DO NOTHING;
